[env:adafruit_feather_m0]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino

# Force PlatformIO to look two levels up at your live library source code
lib_deps =
    symlink://../../
